[2025-05-06T10:08:03.611-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-06T10:08:03.665-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_pipeline.run_etl manual__2025-05-06T13:02:44.719167+00:00 [queued]>
[2025-05-06T10:08:03.668-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_pipeline.run_etl manual__2025-05-06T13:02:44.719167+00:00 [queued]>
[2025-05-06T10:08:03.668-0300] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2025-05-06T10:08:03.678-0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): run_etl> on 2025-05-06 13:02:44.719167+00:00
[2025-05-06T10:08:03.687-0300] {standard_task_runner.py:63} INFO - Started process 53208 to run task
[2025-05-06T10:08:03.691-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_pipeline', 'run_etl', 'manual__2025-05-06T13:02:44.719167+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/mi_primer_dag.py', '--cfg-path', '/tmp/tmp1r67sd75']
[2025-05-06T10:08:03.692-0300] {standard_task_runner.py:91} INFO - Job 70: Subtask run_etl
[2025-05-06T10:08:03.716-0300] {task_command.py:426} INFO - Running <TaskInstance: crypto_pipeline.run_etl manual__2025-05-06T13:02:44.719167+00:00 [running]> on host facuvega
[2025-05-06T10:08:03.752-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='crypto_pipeline' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T13:02:44.719167+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-06T13:02:44.719167+00:00'
[2025-05-06T10:08:03.754-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-06T10:08:03.754-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-06T10:08:03.755-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /home/facuvega/Descargas/crypto-etl-airflow/scripts/etl.py']
[2025-05-06T10:08:03.772-0300] {subprocess.py:86} INFO - Output:
[2025-05-06T10:08:05.114-0300] {subprocess.py:93} INFO - ⏳ Ejecutando ETL...
[2025-05-06T10:08:05.115-0300] {subprocess.py:93} INFO - ✅ Datos validados correctamente
[2025-05-06T10:08:05.115-0300] {subprocess.py:93} INFO - [INFO] La base de datos ya existe en: /home/facuvega/Descargas/crypto-etl-airflow/db/crypto.db
[2025-05-06T10:08:05.115-0300] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-06T10:08:05.115-0300] {subprocess.py:93} INFO -   File "/home/facuvega/Descargas/crypto-etl-airflow/scripts/etl.py", line 119, in <module>
[2025-05-06T10:08:05.115-0300] {subprocess.py:93} INFO -     etl()
[2025-05-06T10:08:05.115-0300] {subprocess.py:93} INFO -   File "/home/facuvega/Descargas/crypto-etl-airflow/scripts/etl.py", line 113, in etl
[2025-05-06T10:08:05.115-0300] {subprocess.py:93} INFO -     dataLoad(crypto_df)
[2025-05-06T10:08:05.116-0300] {subprocess.py:93} INFO -   File "/home/facuvega/Descargas/crypto-etl-airflow/scripts/etl.py", line 66, in dataLoad
[2025-05-06T10:08:05.116-0300] {subprocess.py:93} INFO -     cursor.execute("""
[2025-05-06T10:08:05.116-0300] {subprocess.py:93} INFO - sqlite3.OperationalError: no such table: cryptos
[2025-05-06T10:08:05.228-0300] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-06T10:08:05.229-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-06T10:08:05.235-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-06T10:08:05.239-0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=crypto_pipeline, task_id=run_etl, execution_date=20250506T130244, start_date=20250506T130803, end_date=20250506T130805
[2025-05-06T10:08:05.248-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 70 for task run_etl (Bash command failed. The command returned a non-zero exit code 1.; 53208)
[2025-05-06T10:08:05.286-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-06T10:08:05.300-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-06T10:08:05.305-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
