[2025-05-04T03:50:23.861-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-04T03:50:23.926-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_pipeline.run_etl scheduled__2025-05-03T00:00:00+00:00 [queued]>
[2025-05-04T03:50:23.934-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_pipeline.run_etl scheduled__2025-05-03T00:00:00+00:00 [queued]>
[2025-05-04T03:50:23.934-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-05-04T03:50:23.948-0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): run_etl> on 2025-05-03 00:00:00+00:00
[2025-05-04T03:50:23.962-0300] {standard_task_runner.py:63} INFO - Started process 19376 to run task
[2025-05-04T03:50:23.965-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_pipeline', 'run_etl', 'scheduled__2025-05-03T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/mi_primer_dag.py', '--cfg-path', '/tmp/tmpjhljs0y0']
[2025-05-04T03:50:23.967-0300] {standard_task_runner.py:91} INFO - Job 36: Subtask run_etl
[2025-05-04T03:50:24.033-0300] {task_command.py:426} INFO - Running <TaskInstance: crypto_pipeline.run_etl scheduled__2025-05-03T00:00:00+00:00 [running]> on host facuvega
[2025-05-04T03:50:24.085-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='crypto_pipeline' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-03T00:00:00+00:00'
[2025-05-04T03:50:24.089-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-04T03:50:24.090-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-04T03:50:24.099-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python scripts/etl.py']
[2025-05-04T03:50:24.122-0300] {subprocess.py:86} INFO - Output:
[2025-05-04T03:50:24.151-0300] {subprocess.py:93} INFO - python: can't open file '/tmp/airflowtmp9xdwwn24/scripts/etl.py': [Errno 2] No such file or directory
[2025-05-04T03:50:24.155-0300] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-04T03:50:24.155-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-04T03:50:24.165-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-04T03:50:24.176-0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_pipeline, task_id=run_etl, execution_date=20250503T000000, start_date=20250504T065023, end_date=20250504T065024
[2025-05-04T03:50:24.205-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 36 for task run_etl (Bash command failed. The command returned a non-zero exit code 2.; 19376)
[2025-05-04T03:50:24.266-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-04T03:50:24.284-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-04T03:50:24.285-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
