[2025-05-03T05:17:22.915-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-03T05:17:22.957-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_pipeline.run_etl manual__2025-05-03T08:12:10.849823+00:00 [queued]>
[2025-05-03T05:17:22.962-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_pipeline.run_etl manual__2025-05-03T08:12:10.849823+00:00 [queued]>
[2025-05-03T05:17:22.962-0300] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2025-05-03T05:17:22.983-0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): run_etl> on 2025-05-03 08:12:10.849823+00:00
[2025-05-03T05:17:22.997-0300] {standard_task_runner.py:63} INFO - Started process 33894 to run task
[2025-05-03T05:17:23.002-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_pipeline', 'run_etl', 'manual__2025-05-03T08:12:10.849823+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/mi_primer_dag.py', '--cfg-path', '/tmp/tmpiozi8f4n']
[2025-05-03T05:17:23.006-0300] {standard_task_runner.py:91} INFO - Job 15: Subtask run_etl
[2025-05-03T05:17:23.054-0300] {task_command.py:426} INFO - Running <TaskInstance: crypto_pipeline.run_etl manual__2025-05-03T08:12:10.849823+00:00 [running]> on host facuvega
[2025-05-03T05:17:23.109-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='crypto_pipeline' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T08:12:10.849823+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-03T08:12:10.849823+00:00'
[2025-05-03T05:17:23.111-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-03T05:17:23.112-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-03T05:17:23.113-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /Descargas/crypto-etl-airflow/scripts/etl.py']
[2025-05-03T05:17:23.139-0300] {subprocess.py:86} INFO - Output:
[2025-05-03T05:17:23.174-0300] {subprocess.py:93} INFO - python: can't open file '/Descargas/crypto-etl-airflow/scripts/etl.py': [Errno 2] No such file or directory
[2025-05-03T05:17:23.179-0300] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-03T05:17:23.180-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-03T05:17:23.188-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-03T05:17:23.193-0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=crypto_pipeline, task_id=run_etl, execution_date=20250503T081210, start_date=20250503T081722, end_date=20250503T081723
[2025-05-03T05:17:23.201-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task run_etl (Bash command failed. The command returned a non-zero exit code 2.; 33894)
[2025-05-03T05:17:23.222-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-03T05:17:23.238-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T05:17:23.241-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
