[2025-05-03T05:34:47.389-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-03T05:34:47.418-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_pipeline.run_prediction manual__2025-05-03T08:34:28.983757+00:00 [queued]>
[2025-05-03T05:34:47.422-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_pipeline.run_prediction manual__2025-05-03T08:34:28.983757+00:00 [queued]>
[2025-05-03T05:34:47.422-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-05-03T05:34:47.430-0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): run_prediction> on 2025-05-03 08:34:28.983757+00:00
[2025-05-03T05:34:47.438-0300] {standard_task_runner.py:63} INFO - Started process 42672 to run task
[2025-05-03T05:34:47.444-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_pipeline', 'run_prediction', 'manual__2025-05-03T08:34:28.983757+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/mi_primer_dag.py', '--cfg-path', '/tmp/tmp36yhaxse']
[2025-05-03T05:34:47.447-0300] {standard_task_runner.py:91} INFO - Job 22: Subtask run_prediction
[2025-05-03T05:34:47.479-0300] {task_command.py:426} INFO - Running <TaskInstance: crypto_pipeline.run_prediction manual__2025-05-03T08:34:28.983757+00:00 [running]> on host facuvega
[2025-05-03T05:34:47.528-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='crypto_pipeline' AIRFLOW_CTX_TASK_ID='run_prediction' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T08:34:28.983757+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-03T08:34:28.983757+00:00'
[2025-05-03T05:34:47.530-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-03T05:34:47.531-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-03T05:34:47.531-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /home/facuvega/Descargas/crypto-etl-airflow/scripts/main.py']
[2025-05-03T05:34:47.562-0300] {subprocess.py:86} INFO - Output:
[2025-05-03T05:34:47.622-0300] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-03T05:34:47.632-0300] {subprocess.py:93} INFO -   File "/home/facuvega/Descargas/crypto-etl-airflow/scripts/main.py", line 1, in <module>
[2025-05-03T05:34:47.638-0300] {subprocess.py:93} INFO -     from data.data_load import load_data
[2025-05-03T05:34:47.649-0300] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'data'
[2025-05-03T05:34:47.649-0300] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-03T05:34:47.650-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-03T05:34:47.685-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-03T05:34:47.703-0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_pipeline, task_id=run_prediction, execution_date=20250503T083428, start_date=20250503T083447, end_date=20250503T083447
[2025-05-03T05:34:47.717-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 22 for task run_prediction (Bash command failed. The command returned a non-zero exit code 1.; 42672)
[2025-05-03T05:34:47.743-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-03T05:34:47.756-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T05:34:47.757-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
