[2025-05-03T05:39:51.234-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-03T05:39:51.252-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_pipeline.run_prediction manual__2025-05-03T08:34:28.983757+00:00 [queued]>
[2025-05-03T05:39:51.255-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_pipeline.run_prediction manual__2025-05-03T08:34:28.983757+00:00 [queued]>
[2025-05-03T05:39:51.256-0300] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2025-05-03T05:39:51.263-0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): run_prediction> on 2025-05-03 08:34:28.983757+00:00
[2025-05-03T05:39:51.272-0300] {standard_task_runner.py:63} INFO - Started process 46159 to run task
[2025-05-03T05:39:51.275-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_pipeline', 'run_prediction', 'manual__2025-05-03T08:34:28.983757+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/mi_primer_dag.py', '--cfg-path', '/tmp/tmpwi71bgdt']
[2025-05-03T05:39:51.277-0300] {standard_task_runner.py:91} INFO - Job 23: Subtask run_prediction
[2025-05-03T05:39:51.313-0300] {task_command.py:426} INFO - Running <TaskInstance: crypto_pipeline.run_prediction manual__2025-05-03T08:34:28.983757+00:00 [running]> on host facuvega
[2025-05-03T05:39:51.366-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='crypto_pipeline' AIRFLOW_CTX_TASK_ID='run_prediction' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T08:34:28.983757+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-03T08:34:28.983757+00:00'
[2025-05-03T05:39:51.368-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-03T05:39:51.369-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-03T05:39:51.371-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /home/facuvega/Descargas/crypto-etl-airflow/scripts/main.py']
[2025-05-03T05:39:51.390-0300] {subprocess.py:86} INFO - Output:
[2025-05-03T05:39:51.416-0300] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-03T05:39:51.416-0300] {subprocess.py:93} INFO -   File "/home/facuvega/Descargas/crypto-etl-airflow/scripts/main.py", line 1, in <module>
[2025-05-03T05:39:51.416-0300] {subprocess.py:93} INFO -     from data.data_load import load_data
[2025-05-03T05:39:51.417-0300] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'data'
[2025-05-03T05:39:51.419-0300] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-03T05:39:51.419-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-03T05:39:51.425-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-03T05:39:51.429-0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=crypto_pipeline, task_id=run_prediction, execution_date=20250503T083428, start_date=20250503T083951, end_date=20250503T083951
[2025-05-03T05:39:51.445-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task run_prediction (Bash command failed. The command returned a non-zero exit code 1.; 46159)
[2025-05-03T05:39:51.494-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-03T05:39:51.517-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T05:39:51.518-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
