[2025-05-06T10:22:49.774-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-06T10:22:49.816-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_pipeline.run_etl manual__2025-05-06T13:22:39.752635+00:00 [queued]>
[2025-05-06T10:22:49.829-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_pipeline.run_etl manual__2025-05-06T13:22:39.752635+00:00 [queued]>
[2025-05-06T10:22:49.830-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-05-06T10:22:49.840-0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): run_etl> on 2025-05-06 13:22:39.752635+00:00
[2025-05-06T10:22:49.852-0300] {standard_task_runner.py:63} INFO - Started process 58831 to run task
[2025-05-06T10:22:49.855-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_pipeline', 'run_etl', 'manual__2025-05-06T13:22:39.752635+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/mi_primer_dag.py', '--cfg-path', '/tmp/tmps75nfjed']
[2025-05-06T10:22:49.857-0300] {standard_task_runner.py:91} INFO - Job 72: Subtask run_etl
[2025-05-06T10:22:49.903-0300] {task_command.py:426} INFO - Running <TaskInstance: crypto_pipeline.run_etl manual__2025-05-06T13:22:39.752635+00:00 [running]> on host facuvega
[2025-05-06T10:22:49.974-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='crypto_pipeline' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T13:22:39.752635+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-06T13:22:39.752635+00:00'
[2025-05-06T10:22:49.976-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-06T10:22:49.977-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-06T10:22:49.977-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /home/facuvega/Descargas/crypto-etl-airflow/scripts/etl.py']
[2025-05-06T10:22:50.007-0300] {subprocess.py:86} INFO - Output:
[2025-05-06T10:22:51.935-0300] {subprocess.py:93} INFO - [DEBUG] DB_PATH absoluto: /home/facuvega/Descargas/crypto-etl-airflow/scripts/db/crypto.db
[2025-05-06T10:22:51.936-0300] {subprocess.py:93} INFO - ✅ Tabla 'cryptos' creada correctamente (si no existía).
[2025-05-06T10:22:51.944-0300] {subprocess.py:93} INFO - ⏳ Ejecutando ETL...
[2025-05-06T10:22:51.944-0300] {subprocess.py:93} INFO - ✅ Datos validados correctamente
[2025-05-06T10:22:51.944-0300] {subprocess.py:93} INFO - [INFO] La base de datos no existe. Ejecutando createTable.py para crearla.
[2025-05-06T10:22:51.944-0300] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-06T10:22:51.945-0300] {subprocess.py:93} INFO -   File "/home/facuvega/Descargas/crypto-etl-airflow/scripts/etl.py", line 124, in <module>
[2025-05-06T10:22:51.945-0300] {subprocess.py:93} INFO -     etl()
[2025-05-06T10:22:51.945-0300] {subprocess.py:93} INFO -   File "/home/facuvega/Descargas/crypto-etl-airflow/scripts/etl.py", line 118, in etl
[2025-05-06T10:22:51.945-0300] {subprocess.py:93} INFO -     dataLoad(crypto_df)
[2025-05-06T10:22:51.945-0300] {subprocess.py:93} INFO -   File "/home/facuvega/Descargas/crypto-etl-airflow/scripts/etl.py", line 59, in dataLoad
[2025-05-06T10:22:51.945-0300] {subprocess.py:93} INFO -     conn = sqlite3.connect(DB_PATH)
[2025-05-06T10:22:51.945-0300] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-06T10:22:51.945-0300] {subprocess.py:93} INFO - sqlite3.OperationalError: unable to open database file
[2025-05-06T10:22:52.094-0300] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-06T10:22:52.094-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-06T10:22:52.100-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-06T10:22:52.105-0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_pipeline, task_id=run_etl, execution_date=20250506T132239, start_date=20250506T132249, end_date=20250506T132252
[2025-05-06T10:22:52.114-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 72 for task run_etl (Bash command failed. The command returned a non-zero exit code 1.; 58831)
[2025-05-06T10:22:52.153-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-06T10:22:52.169-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-06T10:22:52.170-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
