[2025-05-03T05:14:47.730-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-03T05:14:47.765-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_pipeline.run_etl manual__2025-05-03T08:09:36.127444+00:00 [queued]>
[2025-05-03T05:14:47.771-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_pipeline.run_etl manual__2025-05-03T08:09:36.127444+00:00 [queued]>
[2025-05-03T05:14:47.771-0300] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2025-05-03T05:14:47.784-0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): run_etl> on 2025-05-03 08:09:36.127444+00:00
[2025-05-03T05:14:47.791-0300] {standard_task_runner.py:63} INFO - Started process 31893 to run task
[2025-05-03T05:14:47.802-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_pipeline', 'run_etl', 'manual__2025-05-03T08:09:36.127444+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/mi_primer_dag.py', '--cfg-path', '/tmp/tmpwxgc6i9o']
[2025-05-03T05:14:47.805-0300] {standard_task_runner.py:91} INFO - Job 14: Subtask run_etl
[2025-05-03T05:14:47.836-0300] {task_command.py:426} INFO - Running <TaskInstance: crypto_pipeline.run_etl manual__2025-05-03T08:09:36.127444+00:00 [running]> on host facuvega
[2025-05-03T05:14:47.869-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='crypto_pipeline' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T08:09:36.127444+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-03T08:09:36.127444+00:00'
[2025-05-03T05:14:47.870-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-03T05:14:47.871-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-03T05:14:47.872-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /Descargas/crypto-etl-airflow/scripts/etl.py']
[2025-05-03T05:14:47.887-0300] {subprocess.py:86} INFO - Output:
[2025-05-03T05:14:47.909-0300] {subprocess.py:93} INFO - python: can't open file '/Descargas/crypto-etl-airflow/scripts/etl.py': [Errno 2] No such file or directory
[2025-05-03T05:14:47.912-0300] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-03T05:14:47.915-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-03T05:14:47.923-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-03T05:14:47.930-0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=crypto_pipeline, task_id=run_etl, execution_date=20250503T080936, start_date=20250503T081447, end_date=20250503T081447
[2025-05-03T05:14:47.939-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task run_etl (Bash command failed. The command returned a non-zero exit code 2.; 31893)
[2025-05-03T05:14:47.982-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-03T05:14:47.998-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T05:14:48.002-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
