[2025-05-04T04:23:21.712-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-04T04:23:21.788-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_pipeline.run_etl manual__2025-05-04T07:23:10.515958+00:00 [queued]>
[2025-05-04T04:23:21.794-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_pipeline.run_etl manual__2025-05-04T07:23:10.515958+00:00 [queued]>
[2025-05-04T04:23:21.794-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-05-04T04:23:21.818-0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): run_etl> on 2025-05-04 07:23:10.515958+00:00
[2025-05-04T04:23:21.833-0300] {standard_task_runner.py:63} INFO - Started process 34609 to run task
[2025-05-04T04:23:21.836-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_pipeline', 'run_etl', 'manual__2025-05-04T07:23:10.515958+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/mi_primer_dag.py', '--cfg-path', '/tmp/tmp3_9bycw2']
[2025-05-04T04:23:21.838-0300] {standard_task_runner.py:91} INFO - Job 51: Subtask run_etl
[2025-05-04T04:23:21.878-0300] {task_command.py:426} INFO - Running <TaskInstance: crypto_pipeline.run_etl manual__2025-05-04T07:23:10.515958+00:00 [running]> on host facuvega
[2025-05-04T04:23:21.952-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='crypto_pipeline' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T07:23:10.515958+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-04T07:23:10.515958+00:00'
[2025-05-04T04:23:21.955-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-04T04:23:21.956-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-04T04:23:21.959-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /home/facuvega/Descargas/crypto-etl-airflow/scripts/etl.py']
[2025-05-04T04:23:21.986-0300] {subprocess.py:86} INFO - Output:
[2025-05-04T04:23:23.632-0300] {subprocess.py:93} INFO - ‚úÖ Tabla 'cryptos' creada correctamente.
[2025-05-04T04:23:23.636-0300] {subprocess.py:93} INFO - ‚è≥ Ejecutando ETL...
[2025-05-04T04:23:23.636-0300] {subprocess.py:93} INFO - ‚úÖ Datos validados correctamente
[2025-05-04T04:23:23.636-0300] {subprocess.py:93} INFO - üîß Base de datos no encontrada. Creando base y tabla...
[2025-05-04T04:23:23.636-0300] {subprocess.py:93} INFO - ‚ñ∂ Ejecutando script: /home/facuvega/Descargas/crypto-etl-airflow/scripts/createTable.py
[2025-05-04T04:23:23.637-0300] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-04T04:23:23.637-0300] {subprocess.py:93} INFO -   File "/home/facuvega/Descargas/crypto-etl-airflow/scripts/etl.py", line 136, in <module>
[2025-05-04T04:23:23.637-0300] {subprocess.py:93} INFO -     etl()
[2025-05-04T04:23:23.637-0300] {subprocess.py:93} INFO -   File "/home/facuvega/Descargas/crypto-etl-airflow/scripts/etl.py", line 130, in etl
[2025-05-04T04:23:23.637-0300] {subprocess.py:93} INFO -     dataLoad(crypto_df)
[2025-05-04T04:23:23.637-0300] {subprocess.py:93} INFO -   File "/home/facuvega/Descargas/crypto-etl-airflow/scripts/etl.py", line 63, in dataLoad
[2025-05-04T04:23:23.637-0300] {subprocess.py:93} INFO -     if not table_exists:
[2025-05-04T04:23:23.637-0300] {subprocess.py:93} INFO -            ^^^^^^^^^^^^
[2025-05-04T04:23:23.637-0300] {subprocess.py:93} INFO - UnboundLocalError: cannot access local variable 'table_exists' where it is not associated with a value
[2025-05-04T04:23:23.781-0300] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-04T04:23:23.782-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-04T04:23:23.789-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/facuvega/Descargas/crypto-etl-airflow/airflow-apache/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-04T04:23:23.794-0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_pipeline, task_id=run_etl, execution_date=20250504T072310, start_date=20250504T072321, end_date=20250504T072323
[2025-05-04T04:23:23.806-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 51 for task run_etl (Bash command failed. The command returned a non-zero exit code 1.; 34609)
[2025-05-04T04:23:23.860-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-04T04:23:23.875-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-04T04:23:23.876-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
